### ISSUE TITLE
滋糍一下

### ISSUE THREAD

**Issue by Lsy1992** [CarGuo/VideoRecord#1]

**Comment by Lsy1992** [comment]
顺便问问：
1、这个录制的时长可否控制
2、录制完毕后的视频文件可否压缩(缩短上传时间)
3、是否考虑增加美颜功能 ...

**Comment by CarGuo** [comment]
灰常感泄~录制长度在RecordActivity的clickRecord里面有，那个61秒说的就是录制一分钟的最大限制。关于压缩的，你可以通过配置MediaRecorder的帧数和码率来达到setVideoFrameRate和setVideoEncodingBitRate减低，不过太低了反而不清晰。如果是很长的视频的话，推荐还是找FFPMEG录制类型的，美颜功能的话也是基于这种模式的，录制的时候通过FFMPEG的图片还有音频同步生成，最后合并到一块，这时候基于图片做美颜效果，就是不适合懒人模式就对了。后面有时候整一个类似的话。

最后说一句，拍完压缩视频这种行为推荐还是不要，因为不同手机的浮点处理差的太多了，压缩时间不是很可控。

**Comment by Lsy1992** [comment]
(⊙o⊙)哦 ，是吗郭司机，也不需要录制多长的，毕竟手机端性能摆在那，录一个像微信那种的小视频，这种如果不压缩的话，录10秒钟超清的起码几十M大小了吧

**Comment by CarGuo** [comment]
现在这个的话，因为码率和帧数都相对不高，然后是640*480的尺寸的，手机上看起来效果还过得去。然后大小一般都是20秒的话，大概2M左右吧，我印象中，手机可能会有些差异，应该不会特别大。
